apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: swagger-aggregator-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: swagger-aggregator-service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: swagger-aggregator-role-binding
subjects:
- kind: ServiceAccount
  name: swagger-aggregator-service-account
roleRef:
  kind: Role
  name: swagger-aggregator-role
  apiGroup: rbac.authorization.k8s.io


